# Generated by Django 4.0.6 on 2022-07-12 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_feeding_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='breed',
            new_name='topic',
        ),
    ]
