# Generated by Django 4.0.6 on 2022-07-12 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_breed_card_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='age',
            new_name='hours',
        ),
    ]
