# Generated by Django 4.0.6 on 2022-07-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_age_card_hours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toy',
            old_name='color',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='toy',
            name='name',
        ),
        migrations.AddField(
            model_name='toy',
            name='link',
            field=models.CharField(default=1, max_length=550),
            preserve_default=False,
        ),
    ]
