# Generated by Django 4.0.6 on 2022-07-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_color_toy_description_remove_toy_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='description',
            field=models.TextField(),
        ),
    ]
