# Generated by Django 4.0.6 on 2022-07-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_toy_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeding',
            name='meal',
        ),
        migrations.AddField(
            model_name='feeding',
            name='focus',
            field=models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], default='H', max_length=1),
        ),
    ]
