# Generated by Django 4.0.6 on 2022-07-12 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_feeding_meal_feeding_focus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feeding',
            old_name='focus',
            new_name='heal',
        ),
    ]
