# Generated by Django 4.0.6 on 2022-07-12 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_rename_heal_feeding_meal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feeding',
            old_name='meal',
            new_name='heal',
        ),
    ]
