# Generated by Django 4.0.6 on 2022-07-12 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_rename_meal_feeding_heal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feeding',
            old_name='heal',
            new_name='focus',
        ),
    ]
