# Generated by Django 4.0.6 on 2022-07-13 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_rename_toy_resource_rename_toys_card_resources'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feeding',
            new_name='Session',
        ),
    ]
